CREATE TABLE IF NOT EXISTS offer_letters (
    id INT AUTO_INCREMENT PRIMARY KEY,
    offer_no VARCHAR(20) NOT NULL UNIQUE,
    employee_id INT NULL,
    candidate_name VARCHAR(150) NOT NULL,
    designation VARCHAR(150) DEFAULT '',
    department VARCHAR(100) DEFAULT '',
    nationality VARCHAR(100) DEFAULT '',
    offer_date DATE NOT NULL,
    joining_date DATE NULL,
    basic_salary DECIMAL(10,2) DEFAULT 0,
    housing_allowance DECIMAL(10,2) DEFAULT 0,
    transport_allowance DECIMAL(10,2) DEFAULT 0,
    other_allowance DECIMAL(10,2) DEFAULT 0,
    probation_period VARCHAR(50) DEFAULT '3 months',
    working_hours VARCHAR(50) DEFAULT '8 hours per day, 5 days a week',
    annual_leave VARCHAR(50) DEFAULT '30 days per year',
    notice_period VARCHAR(50) DEFAULT '30 days',
    issued_by VARCHAR(100) DEFAULT '',
    issued_by_title VARCHAR(100) DEFAULT '',
    notes TEXT DEFAULT '',
    created_by INT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
